---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - zigbee-controller
      containers:
        - image: koenkk/zigbee2mqtt:1.25.1
          name: zigbee2mqtt
          volumeMounts:
          - mountPath: /dev/ttyUSB0
            name: zzh
          - mountPath: /app/data
            name: data
          securityContext:
            privileged: true
          ports:
            - containerPort: 8989
      volumes:
      - name: zzh
        hostPath:
          path: /dev/ttyUSB0
      - name: data
        persistentVolumeClaim:
          claimName: zigbee2mqtt-v2
