---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: default
  annotations:
    kubernetes.io/ingress.class: external
    nginx.ingress.kubernetes.io/enable-global-auth: 'false'
spec:
  rules:
    - host: sko.ai
      http:
        paths:
          - backend:
              service:
                name: blog
                port:
                  number: 8080
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: blog
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: default
  labels:
    app: blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: blog
          image: harbor.sko.ai/library/blog:1.0.7
          ports:
            - name: blog
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /blog
              port: 8080
          livenessProbe:
            httpGet:
              path: /blog
              port: 8080
          resources:
            limits:
              cpu: 10m
              memory: 100Mi
