apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    configuration.yml: ENC[AES256_GCM,data:2Kd8mktuJxxLfGLyM/mRJ/WR/ICvZTdtQbyo7+PBdC+VYj1B0gdn1Wvm0SzSZPPXrQ7HpT0rc/iJwjWsaSnQDr6K0ZQT+imhHtOOnUb3oxSz7bvTZxtE9oWRMhOtfSPnE+wCSeg6ivl9qVUmjPBQzh2j4KtKzxalii6shJ2YajiIw+UFkHOb8BR7Dfgle96l1O9T1e7C+VhqOfVLZ99DC1KjYLrTuUALAYuEKUvoJyfKSCKfwPtpyw2mgVeeWqfXf/3sTMP05KVLyzsqUkngH2kFzDnhOfC5agZW3FYipAsKVWKRbiV+Numolcm/lXQ2hW1rZWA7CgXSHCKiQmfZp6Or5yBzR3ebZa7z5ucmd0FQ8RNt74/q5jZf35Fb6gax4dzW+wkBFycUk6Wn0SBlTmWGDS9j1p/HDBy93Xe3omVUSAGORl1dijEQ+lXk8vqaKlEUGjXYPDhmtS1IAshwxcMA/40AM+KdsWRp13jf1dmmeDSF80XjCgbdkC/6mnGhTf6vNoLZgWSyucW/DZ9Ubfai8z3o9PbhYhCbEuc+2rEUKgnl9NZgc/41tIyyLhUGpTooM3thnI0/07ICFzqm01aNgrbQHeeEXvrKiX96WMx2ue7qyozV2gAHuIAlGO41XgDyGLSTeOtJw80qsUQrO0VKw9IYBoLECJSvfcyGYovdZ+5rLJBSJb20TQPZ9axf83t8nM+luRwz2oFBZZk/3Garw6VnNTPr09lrn27OeXmo9A5b+PNkG/g9Zqbda7SDpfZ7tNgkoCH/s849/R6sEqp09kImkFvX89em4XoCHCyr9/13Ujm1BrhpAWgnjT7OhuZqJ/S0uKL/G9PHLrlpunxAz6JMuo5KwWpAJ8I/lwaCF3mwY7Jhgqev8neZdkBgC4q5BrLAnoM+cyNodQ+a8kflk+W5Ew+K+U8adxE1RB/3BlBldKItDM5mc0BsxF+5cKEabBzhnTG+1teBPT+BN6+IXlgq1NFvn0WkcbzZ9gkWYDUe1r1Er8RSkGEljqW2HVzszqk+eeP2yu1UHcbUnjDhG3YQXFRexpiaJ9m1jbgnR10dWT/yBbE0yeL0CYai3Efc2EwOkblnxXOFpUvavjLp9RiblBzl75WKCxfF6/8iMs4e2p53TNXy5bcSO/I0weOPctGHckOhc7aGAZN4osDx4pVpZecf3upEGeqBM5EFU1IeNponsF0fj56gAZjEfCF/0x1E9KrU5XqQ/BhgsYlM1wjSkhP33paQztYZd9Io/El8Sj4s1I7XXN34fuVgRFDmjTi1goYzUJ1V9w0zzoQPd33/A9mq3W06wSiMhWRfiWW3FwMGtLwOXhboKRExEjKD2OCGudHijKilHNQjZnuROYx4z6KfjmtSazGlXiRSq+6CsC37E078v/5d03EzPijI4lv9KY/HxqmvebJFSPwb9DIl1HsqUVHDra/eCTCGqLNiizXyV/4apY8HIpyaotjl2V6D5JtXAYQsxdPGD6zQurbl3yzYLdqbQFJ9mnb3GEgV8/KmV+1ZnLhKTES/zfdUwzBH3Tspexo7BL0+ooNXzwDBGcjTVADeBmF7k91+qroS1XuXu2n7CppO7jF+vtmnFhilYzLP+wQfjGqZNN3d+lYJIIEqioqKscZED/eEMonKgLhXJEunoTa9rSUCLTdK4JLxjSdtx+i00kd7vVt9+Io4eVtceuK6M7+UptrpO0QrazsYYRWF8GWs+rfISicUh6V1hl6b69hDrbWo8Lx0n9vDf3hpFHfE/rjZ8cKU9cJLVRs3pV1+yAEVRC6op1d93HMiwZyQpdmsWwTAT0I4u922e3dFceMFL5QuTzuODSWjnLnfr9776QVfe26yKMEoX6pih59VvgdiJL2f275qhNEOQBzRoosi4YCym5H75M3B14iF/gSBVd5pWBHdQks//LVv0rs/uup1MphDu9orCfZS9xSvZoClpqxCsH2v5OFTokhu4sPpQ1uq7BiCkkAXPwVEmtpqrfKaCjRx9dKuiiOSg31+/PBh6w503a9vZRq6NGlNVPDiuBdF0FFABACKkX0XqERpPXNq8C1C8B5XyAWFNGv7a6o2XprPa5Jxjc+KGZc5BEuV,iv:tGm9z7BKl6NapaAK85P7KLSghah5fqNJ0sIQ5SCgIkk=,tag:JQMf+J1c0tQmS2Q5a7YRmQ==,type:str]
    users_database.yml: ENC[AES256_GCM,data:R69qGaew6sTr+GhIJlvRpkdhEI7FAjhv2O60W4u7h5zOomeFELC9tg8Zl9ntpAU7TFoMaMhL6nD52xrik/dAKfyHVEtpmJD2NVuOYhsx2Wc2ZJxDGczVpWu+QTIKgttKFTgLIQpbERjuLtBfbukwdm1STStEOyp2Qm+78Xo420BGqaz2cLhVBqwDRL5gA3m+sR1sXHIr2XVh2S3V+4oV+fFr7VeNRHCBClKDQ1DfjpZ344+jBUw1okxDiwgfSIvZ512+u3YBvcD3GGc0Pe2isPnt4MZGCUaq1TSVz6w17+7kvxpmc3Tg9aL5/sJ+JW7fzCZtx4PCdI2EGGi9EfQMvkGv1wWyvQJvt/DHqfprtXqHPprxxUYfXjJBQI6zlbZ3clcNg05UvN0WioGIZ460mQ0jjxDFmwlfE/VRYyyI2LPpjYazqX/gMfXGqdgnz3T5n5nMPvk+m2ELLsaZ3MBUlkWcz+cuR+N5V3AGn1jEefA0abcbMv6CUtJIzQckBoE50MnA7+QYwyzm2DVgXWj+/+5pAm3BbTnB1cy8vNBVylbY3A0NGeoGF1wgTLhoUpz0qPGgAnuSKiZy5bJkgWLbA88RiGL6dSwDN3zSNZgRq8uAQ+lrWYwJobacU73u6Og=,iv:ctnnrxdcl/Rfihly2R/4KdxgDcjlpPF7raCPHMtizZ8=,tag:KKmrG9xrdz2KtfsHTZ1Tag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T14:45:38Z"
    mac: ENC[AES256_GCM,data:pMB1G7ntZMPAj/Lpe1BzcVYR+VsTKo7yhKzBsXjLDZokG41qBBFFr8ALOuE0aOzPkaOg2vj6+5TcAJqVF5ohD1mxbVzj040ZKydXkRDFCyK21xtO36xQy3RhnghJDXU5bEq3req7H7YwgO9XWaHLamIs0Q3bqISDIfqmmA0rVl0=,iv:PHpQNM2a45hBlZvhBNtdlpffK6yqkgRSMsh9WVj06r8=,tag:roV8tWmXmzizVzoI3HgEOQ==,type:str]
    pgp:
        - created_at: "2021-03-20T20:10:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA4x50yY5upzjEAv/ZgJisC3UQDUCOpL0Ui+dinnRTDhtkXRmVTbC7ORXAmOU
            rbANQylqI2lGOt+kX2v/PUSP/0DSSzxnrhxl/+iADRs1sfmR1Vg1cQYc4JlGuVvG
            AeX+siGsdh94Ekc6Xhx6v8m8UV4IH5l2ACDFnqGdQI9ETVtmd4SezTnnL25irYfn
            28/CVJd0GY2CKybcWzEsC0ecMAgojhyNJs/QQYnnkMHBD7UuEzwNElI5oFMo/Gpz
            QuDsMNHXOBUK8zSSoSExgHqujz7R282NMAtQxKkXN9STZEUTnvNKv1jaZkDJOAR4
            0XspSeUe/h15MXzN3ieWJfMwkqPyI8ADlPxZtSKKWK4q8qzErVNFIHBf1/cS9sU4
            NzGJabPExFGffPiYfpZ9S46kJHt5aM9kU6LFGSGBrRMZOSR4m9bIjinvIEmf2GO1
            ttcsPVSQEEIZzxFtyGuNXcHmZNl5mmX5b7KaWUDsPCWbijQfEH0nItkqNQuqX6RJ
            duxfhjLForu7z+puySB/C/4sZwtnaEAssDRcVYTPluvlTd3XLGy9zrMbGP8imVdR
            ONLhCJT5Smh2vn5np04xAEoJ0qdUPSh8DlpWIf36Qmkcov1GOBS56L87uv/Y8oc4
            fiHITpEGdnvLSRTtV4NLbeHznekt58TTkiB9EiiBVJXCmkx0FKEuC9QauSTU3P7W
            5vKhpJEfyYYGW5yMe+sYReac5+CFD25HjCcLxmbIX8B19QFWdj407h99dyj3NAKB
            8m5jHx0FLMtkPV8QBqV40G3i8E4a+sTnN8S0OIwJKKNHYCdvlOhM6lGzmFlU1kjD
            qnFIVc8PTVyZ96ZafgV7cVwN348kiqEBtIRuZhSGs8IeB4hVhjGhunjfpMdTH3ed
            T2uyIQvq2HjC5AtISKDLHooF5kgUi7PPh8W3WRWoNtpcW1fqX9rSpxNYmYWAO2VB
            JvTZvVTCYncsRpisAbmjQeUWxLzZKIPHMV9/GGE5sOk0GQPFV75B3G2ghNWIZqes
            yRQM0dQ0tpkS57LrSkc8+vbSXgGBak7QOs56lhHO+L89BlMs52Z6wRLuBbJGO3go
            klPzwwE6JNBKYZFv1A7WtELwijOX2yTNi5gn/W5J5AYTW3zb41cVWIIQ1shktpgu
            n1vU6H3gQncZe5qFLlH2OcM=
            =j+Uq
            -----END PGP MESSAGE-----
          fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
