apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    configuration.yml: ENC[AES256_GCM,data:60AAniilXoCq/O7s7gOJ9RRcCnnwBDZfCwdtUarPhNz88KgdPqKG2//I7gGJ34DEngd6FpaBq12z2B2g0GmgVZI7Kjtxs9dHLeVdKZbTFnSEnQ6oiqizgTN6Md2RQOXvd9F02qI4v/majlG6hlXj6oZLbb/jmtIPRBuzloW0DjC2InfYXImVf/5RcQKh4E21RVB7xQT67+Ec4zWNL3YhdxgXeVrMmlxRixTApwQxKlASMJoi3Ro7EZ6aX0ErT9x2ajpe/iRhXcTlUBS2n+EoHfaRenTI7JyWGPuDw1SgCzYCcWN04WFlHPKEBqJUy40XJnvy5JIBdSO+j7DnPQ9/OdMQfhClMM71d8XLven/DvpC0hcVSswXN75ykd7snQg54h5awq4ph8cTTvlwW5WOCZNn9/wujDLNNhO2zWX3Wu8d3VcBHp/3FnWUY7hqMjXAtA4qLvPsTrpC56Yt9dwp72oeGgp2BT+aZYlXyE/YKeW8QUw2hqd05idi7kkwnSBIQJAwy09GBGCREwFnh1P7RBUaTE71DQEeBxL92ot7MVwc1ijCoOaKHtxmfvdwgeFXJNMF10wpgGyupjekS9PSiyF4sCk9JjObTjCHEuQPQADt5gKDGnIJwoTjT9YAlgX6wpcicNpTE0VWqL65A31XTrYcgsygIWLT0D0anI8/zg7qKUEoxNtwAhAiOiQhYDZG0aUk+3p+GYvvFKCRZHApdun+L5PEbnyxI2sJWtYvLpj7BEZgmbuhnKcZBK+tT0eOpnLee20fjGBzeKu7wy6cWxvyvDNxd0l304wb+M6PC5QYi8+S2YQzdXzKwVpDGn05l46OAbVx5F9aBNtAAZzPk6XuhPGdm3kZTKzPuvbSlMw3zhWo2JPtY0J9B78BNoVNBr3IptvBWwgYO2XUAQVYDP2fAkdAByBai+rhLIIxn30AHKJcnRUg3Y+IBWOKVy5HiaxOIKkpsa3Qhmm3ucgOr9eget8Kw6hInfrkTajvjLNeRrQyL6+6FTttzc4qwCpzFPGezQON/J/8AH9WoXFZQ8/fKbVzQL76d+ecK4i4jX83ko5+zUewcwGi1M7qs6vRILieXZiwD1kU2szx9Lg670cRREFE/R5ISrHjmQaOpNl1eC9zIIRReZLiezOFrjtG8t3/FVgwKSYFAFTxf/AgKqTYtAu1GrxqM900WTDKZ6Yv7n61LLrbxgQ0D/X2mCRS6w9SVodILZFVtIsIgmzcNKgbI6DpDBw9BMFI727Uxv6WuF3kI2wuQ+mWcGZ9pbuXQWTdSjmOIvVMVOUJiRRSIyr+eNn4nfBD+ql1pr6L1tr+8lfuwQaKTz468QZibqzN0FVX8vOJHbUFhqw7wiXUllu4KqRQLB1WyyECeOu1LKCwy6lxnKbnj3HknEj4gIKZ2kTY33uqdmAB3L0CNvPIUlKp+wivL8ZV9MTgP3GsAlTH0QL8deL2K81dWgeGcECv9QR78kiCphYpZCIayjfIdkSBYhB/WvZs9SO7eD+6wMdjlYg9qAzS44jS4zN3hNkrG5qEKECyx6yVxIDCXorg8Xygn+HpsNGeqQkPobXxQIq3FXigs0bUfaFtqsPHb5OjJ1fFUL2qNhiq6x4TNCb3PNJHcgBTBJv/1Yu+SATxgG1EmEY/9iWpRj2Dkn48akWIbPbXEF2Hb8nhwD8sv7M0cEnmVYnlplYOLowIqChqAkKRg1Er33KQqsiYtBaWGOCqQTLa/0mFv4yaF+JczNyFh37mCdNFwsv2HFCJj2QHdguDVhujmk8AIb3G+Bkm241cUXOwRoHyjArRSvF7EqEXx8oVNLrIE6XnalCXM1D9USwfEu8ifHZ8fWyYn6NWVCqt4QVcpE3vMXq/1Rgh9gilirghceri/JzHPIJM/IOVw7UReeJ2FZkuuzLil6PSaXiANNUuMLyiIZwp6JPaIgF82FM2ryLDAzkISslK1aivdS+uIiFG0euU2radOhuwLoE1MVkAwwdiTtAh4cj91YOzI1jJtUuRc3bQnB9lN4B/cslmPZS9vYb4BLQkd1ohReNJp7ctu1vVnwJikoEeaVJ/jRSWdZPCVeb9Z2lyw3snZP7r6bj4JxA2aKh3UVRicp+aN1VgqewzAHShXhRIZTTP6Ks5u5BONERmjE5Kih7Syvw8nSEXZqL4qBg=,iv:lIfG1Uv2zuw41xfikzfvxfmNmKlx447DTsqCaOG3r0k=,tag:8uXjWVgQ9ExR5kxi4OsKQw==,type:str]
    users_database.yml: ENC[AES256_GCM,data:R69qGaew6sTr+GhIJlvRpkdhEI7FAjhv2O60W4u7h5zOomeFELC9tg8Zl9ntpAU7TFoMaMhL6nD52xrik/dAKfyHVEtpmJD2NVuOYhsx2Wc2ZJxDGczVpWu+QTIKgttKFTgLIQpbERjuLtBfbukwdm1STStEOyp2Qm+78Xo420BGqaz2cLhVBqwDRL5gA3m+sR1sXHIr2XVh2S3V+4oV+fFr7VeNRHCBClKDQ1DfjpZ344+jBUw1okxDiwgfSIvZ512+u3YBvcD3GGc0Pe2isPnt4MZGCUaq1TSVz6w17+7kvxpmc3Tg9aL5/sJ+JW7fzCZtx4PCdI2EGGi9EfQMvkGv1wWyvQJvt/DHqfprtXqHPprxxUYfXjJBQI6zlbZ3clcNg05UvN0WioGIZ460mQ0jjxDFmwlfE/VRYyyI2LPpjYazqX/gMfXGqdgnz3T5n5nMPvk+m2ELLsaZ3MBUlkWcz+cuR+N5V3AGn1jEefA0abcbMv6CUtJIzQckBoE50MnA7+QYwyzm2DVgXWj+/+5pAm3BbTnB1cy8vNBVylbY3A0NGeoGF1wgTLhoUpz0qPGgAnuSKiZy5bJkgWLbA88RiGL6dSwDN3zSNZgRq8uAQ+lrWYwJobacU73u6Og=,iv:ctnnrxdcl/Rfihly2R/4KdxgDcjlpPF7raCPHMtizZ8=,tag:KKmrG9xrdz2KtfsHTZ1Tag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-18T23:18:16Z"
    mac: ENC[AES256_GCM,data:NpJWTSlPc9VI25ETR5nO+vz0gNC80sGCpDjnXXQ+M7hOrAgg6xJOZZQnzlM4gpg1Rlym2ZDjJWxFJuxokQt42hXA8UlYTK8SFIvKojAte28W4TXP0wAjWgS33JVJFRnzTYS4KpIrncT4LelA5gswGFAXlx8vwDrESiduufLnKV4=,iv:FbS087FiWjXKsm7ruuucgQNS7eejB94sz2dDRRtVa9M=,tag:WGzStJyKLrzvALCTkfYj5Q==,type:str]
    pgp:
        - created_at: "2021-03-20T20:10:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA4x50yY5upzjEAv/ZgJisC3UQDUCOpL0Ui+dinnRTDhtkXRmVTbC7ORXAmOU
            rbANQylqI2lGOt+kX2v/PUSP/0DSSzxnrhxl/+iADRs1sfmR1Vg1cQYc4JlGuVvG
            AeX+siGsdh94Ekc6Xhx6v8m8UV4IH5l2ACDFnqGdQI9ETVtmd4SezTnnL25irYfn
            28/CVJd0GY2CKybcWzEsC0ecMAgojhyNJs/QQYnnkMHBD7UuEzwNElI5oFMo/Gpz
            QuDsMNHXOBUK8zSSoSExgHqujz7R282NMAtQxKkXN9STZEUTnvNKv1jaZkDJOAR4
            0XspSeUe/h15MXzN3ieWJfMwkqPyI8ADlPxZtSKKWK4q8qzErVNFIHBf1/cS9sU4
            NzGJabPExFGffPiYfpZ9S46kJHt5aM9kU6LFGSGBrRMZOSR4m9bIjinvIEmf2GO1
            ttcsPVSQEEIZzxFtyGuNXcHmZNl5mmX5b7KaWUDsPCWbijQfEH0nItkqNQuqX6RJ
            duxfhjLForu7z+puySB/C/4sZwtnaEAssDRcVYTPluvlTd3XLGy9zrMbGP8imVdR
            ONLhCJT5Smh2vn5np04xAEoJ0qdUPSh8DlpWIf36Qmkcov1GOBS56L87uv/Y8oc4
            fiHITpEGdnvLSRTtV4NLbeHznekt58TTkiB9EiiBVJXCmkx0FKEuC9QauSTU3P7W
            5vKhpJEfyYYGW5yMe+sYReac5+CFD25HjCcLxmbIX8B19QFWdj407h99dyj3NAKB
            8m5jHx0FLMtkPV8QBqV40G3i8E4a+sTnN8S0OIwJKKNHYCdvlOhM6lGzmFlU1kjD
            qnFIVc8PTVyZ96ZafgV7cVwN348kiqEBtIRuZhSGs8IeB4hVhjGhunjfpMdTH3ed
            T2uyIQvq2HjC5AtISKDLHooF5kgUi7PPh8W3WRWoNtpcW1fqX9rSpxNYmYWAO2VB
            JvTZvVTCYncsRpisAbmjQeUWxLzZKIPHMV9/GGE5sOk0GQPFV75B3G2ghNWIZqes
            yRQM0dQ0tpkS57LrSkc8+vbSXgGBak7QOs56lhHO+L89BlMs52Z6wRLuBbJGO3go
            klPzwwE6JNBKYZFv1A7WtELwijOX2yTNi5gn/W5J5AYTW3zb41cVWIIQ1shktpgu
            n1vU6H3gQncZe5qFLlH2OcM=
            =j+Uq
            -----END PGP MESSAGE-----
          fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
