---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1h
  chart:
    spec:
      chart: harbor
      version: 1.9.3
      sourceRef:
        kind: HelmRepository
        name: harbor-charts
        namespace: flux-system
      interval: 1h
  values:
    expose:
      tls:
        # The ingress controller has a default certificate so we don't need to configure it
        certSource: none
      ingress:
        annotations:
          kubernetes.io/ingress.class: internal
          nginx.ingress.kubernetes.io/enable-global-auth: 'false'
        hosts:
          core: harbor.sko.ai
    externalURL: https://harbor.sko.ai

    trivy:
      enabled: false
    chartmuseum:
      enabled: false
    notary:
      enabled: false

    # # Enable When you have found good graphs
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true

    portal:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-portal
    core:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-core
    jobservice:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-jobservice
    registry:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-photon
    database:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-db
    redis:
      image:
        repository: ghcr.io/octohelm/harbor/redis-photon
    exporter:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-exporter

    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: registry
        jobservice:
          existingClaim: jobservice
        database:
          existingClaim: database
        redis:
          existingClaim: redis

