apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
- _namespace.yaml
- hr.yaml
- pvcs/database.yaml
- pvcs/jobservice.yaml
- pvcs/redis.yaml
- pvcs/registry.yaml
