---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: media
  labels:
    app: recyclarr
spec:
  schedule: '@daily'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          containers:
            - name: recyclarr-sonarr
              image: ghcr.io/recyclarr/recyclarr:4.0.2@sha256:d7d91ed39b0fc78ba04acc37e84b1a2fc4fe69bef7521aacdf156375f12b03b3
              imagePullPolicy: IfNotPresent
              command:
                - /app/recyclarr/recyclarr
              args:
                - sonarr
              volumeMounts:
                - name: config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
            - name: recyclarr-radarr
              image: ghcr.io/recyclarr/recyclarr:4.0.2@sha256:d7d91ed39b0fc78ba04acc37e84b1a2fc4fe69bef7521aacdf156375f12b03b3
              imagePullPolicy: IfNotPresent
              command:
                - /app/recyclarr/recyclarr
              args:
                - radarr
              volumeMounts:
                - name: config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
          volumes:
            - name: config
              secret:
                secretName: recyclarr-config
