kind: pipeline
type: kubernetes
name: update_flux

steps:
- name: job:update_flux
  image: alpine:3.16
  commands:
  - env
  - apk add git bash perl skopeo
  - wget https://toolkit.fluxcd.io/install.sh -O - | /bin/bash
  - ./scripts/update.sh
  - git diff --exit-code || export DIFF=1
  - \[ -z $DIFF \] || git push origin --delete update/flux || true
  - \[ -z $DIFF \] || git checkout -b update/flux
  - \[ -z $DIFF \] || git config --global user.name 'Flux Updater'
  - \[ -z $DIFF \] || git config --global user.email 'flux@sko.ai'
  - \[ -z $DIFF \] || git commit -a -m 'Auto-update flux version'
  - \[ -z $DIFF \] || git status
  - \[ -z $DIFF \] || git push -o merge_request.create origin update/flux
  - ./scripts/update-images.sh
  - \[ -z $DIFF \] || git push origin --delete update/images || true
  - \[ -z $DIFF \] || git checkout -b update/images
  - \[ -z $DIFF \] || git config --global user.name 'Image Updater'
  - \[ -z $DIFF \] || git config --global user.email 'git@sko.ai'
  - \[ -z $DIFF \] || git commit -a -m 'Auto-update images'
  - \[ -z $DIFF \] || git status
  - \[ -z $DIFF \] || git push -o merge_request.create origin update/images

trigger:
  event:
  - cron
  cron:
  - nightly
    #---
    #kind: pipeline
    #type: kubernetes
    #name: validate_manifest
    #
    #steps:
    #- name: validate_manifests
    #  image: r.sko.ai/vasko/kustomize-eval:0.0.6
    #  commands:
    #  - validate.sh ./cluster
