---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jobservice
  namespace: harbor
spec:
  storageClassName: ssd-raid5
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
