apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-subdir
spec:
  interval: 1h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.12'
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir
        namespace: flux-system
      interval: 1h
  values:
    nfs:
      server: pi0
      path: /srv/nfs
      mountOptions:
      - nfsvers=4.2
      - hard
      - noac
      - nocto
      - noacl
      - rsize=8192
      - wsize=8192
      - async
      - retrans=3
      - timeo=600
    storageClass:
      defaultClass: true
      provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner
