---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photoprismdb-pvc-v1
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.1Gi
