---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving
  template:
    metadata:
      labels:
        app: serving
    spec:
      containers:
        - image: tensorflow/serving:v2.17.2
          env:
            - name: TENSORFLOW_API
              value: 'http://blind:8501/v1/models/model:predict'
          name: serving
          command: [sh]
          args:
            - -c
            - /serving config init && /serving users add vasko foo && /serving
              users add leane foo && /serving config set --auth.method=proxy --auth.header=Remote-User
              && /serving
          ports:
            - containerPort: 8501
