---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: index-photoprism
  namespace: default
spec:
  schedule: 0 */1 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: photoprism-index
              image: vaskozl/photoprism:20210909
              resources:
                requests:
                  memory: 1.5Gi
                  cpu: 300m
                limits:
                  memory: 1.5Gi
                  cpu: 300m
              imagePullPolicy: IfNotPresent
              env:
              - name: TENSORFLOW_API
                value: 'http://serving:8501/v1/models/model:predict'
              - name: PHOTOPRISM_DETECT_NSFW
                value: 'false'
              - name: PHOTOPRISM_DISABLE_FFMPEG
                value: 'true'
              - name: PHOTOPRISM_DATABASE_DRIVER 
                value: "mysql"
              - name: PHOTOPRISM_DATABASE_SERVER
                value: "photoprismdb:3306"
              - name: PHOTOPRISM_DATABASE_NAME
                value: "photoprism"
              - name: PHOTOPRISM_DATABASE_PASSWORD
                value: "photoprism"
              - name: PHOTOPRISM_DATABASE_USER
                value: "root"
              args:
                - sh
                - -c
                - "curl  https://storage.googleapis.com/bit_models/imagenet21k_wordnet_lemmas.txt --output /photoprism/assets/nasnet/labels-21k.txt && /photoprism/bin/photoprism index"
              volumeMounts:
                - mountPath: /photoprism/storage
                  name: config
                - mountPath: /photoprism/originals
                  name: originals
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: photoprism-v2
            - name: originals
              persistentVolumeClaim:
                claimName: original-photos-v3
          restartPolicy: Never
      parallelism: 1
