---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  chart:
    spec:
      chart: photoprism
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 2.2.1
  interval: 1h
  values:
    env:
      PHOTOPRISM_SITE_URL: https://p.sko.ai/
      PHOTOPRISM_PUBLIC: true
      PHOTOPRISM_DEBUG: false
      PHOTOPRISM_THUMB_SIZE: 1280
      PHOTOPRISM_THUMB_UNCACHED: true
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 1280
      TENSORFLOW_API: 'http://blind:8501/v1/models/model:predict'
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_DISABLE_FFMPEG: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprismdb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "root"
      PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
      PHOTOPRISM_DISABLE_FFMPEG: true
    image:
      repository: vaskozl/photoprism
      tag: '20210909'
    resources:
      requests:
        cpu: 100m
        memory: 0.5Gi
      limits:
        cpu: 2000m
        memory: 1.0Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal
        nginx.ingress.kubernetes.io/auth-url: https://gate.sko.ai/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://gate.sko.ai/
      hosts:
        - host: p.sko.ai
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - p.sko.ai
    persistence:
      config:
        enabled: true
        existingClaim: photoprism-v2
      originals:
        enabled: true
        existingClaim: original-photos-v3
        readOnly: true
