---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photoprism-v2
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
