apiVersion: batch/v1
kind: CronJob
metadata:
  name: archiver
spec:
  successfulJobsHistoryLimit: 3
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: '@midnight'
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            intent: management
          containers:
            - name: logrotate
              image: public.ecr.aws/docker/library/busybox:1.36.0@sha256:b5d6fe0712636ceb7430189de28819e195e8966372edfc2d9409d79402a0dc16
              command:
                - find
              args:
                - /var/logs/k8s
                - -type
                - f
                - -mtime
                - '+30'
                - -delete
                - -print
              resources:
                requests:
                  cpu: 10m
                  memory: 10Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              volumeMounts:
              - name: logging-pvc
                mountPath: /var/logs/k8s
          restartPolicy: Never
          volumes:
          - name: logging-pvc
            persistentVolumeClaim:
              claimName: logging-pvc
