---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr
  annotations:
    nginx.ingress.kubernetes.io/enable-global-auth: 'false'
    nginx.ingress.kubernetes.io/limit-connections: '15'
    nginx.ingress.kubernetes.io/limit-rpm: '300'
spec:
  ingressClassName: external
  rules:
    - host: requests.sko.ai
      http:
        paths:
          - backend:
              service:
                name: overseerr
                port: 
                  number: 80
            path: /
            pathType: Prefix
