apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: torrent
spec:
  chart:
    spec:
      chart: flood
      interval: 30m
      sourceRef:
        name: k8s-at-home
        namespace: default
        kind: HelmRepository
      version: 2.4.0
  interval: 5m
  values:
    image:
      pullPolicy: Always
      repository: jesec/flood
      tag: 4.7.0
    env:
      FLOOD_OPTION_AUTH: none
      FLOOD_OPTION_QBPASS: ${FLOOD_OPTION_QBPASS}
      FLOOD_OPTION_QBURL: http://syno:55555
      FLOOD_OPTION_QBUSER: vsz
      FLOOD_OPTION_RUNDIR: /data
    resources:
      limits:
        memory: 1500Mi
      requests:
        cpu: 500m
        memory: 250Mi
    controllerType: deployment
    ingress:
      enabled: true
      hosts:
      - host: fl.sko.ai
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - fl.sko.ai
    persistence:
      data:
        accessMode: ReadWriteOnce
        enabled: true
        size: 1Gi
        storageClass: nfs-client
    podSecurityContext:
      fsGroup: 1001
      runAsGroup: 1001
      runAsUser: 1001
