---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: torrent
spec:
  limits:
    - default:
        cpu: 700m
      defaultRequest:
        cpu: 100m
      type: Container
