---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: torrent
spec:
  limits:
    - default:
        cpu: 0.7
      defaultRequest:
        cpu: 0.1
      type: Container
