---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 1h
  chart:
    spec:
      chart: gitlab
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 1h
  values:
    global:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      edition: ce
      hosts:
        domain: sko.ai
      ingress:
        class: internal
        annotations:
          nginx.ingress.kubernetes.io/enable-global-auth: 'false'
        # Wildcard is configured by default
        configureCertmanager: false
        # TLS is enabled by default
        tls:
          enabled: false
      kas:
        enabled: false
      pages:
        enabled: true
      email:
        display_name: 'GitLab'
        from: 'gitlab@sko.ai'
        reply_to: 'noreply@sko.ai'
      smtp:
        enabled: true
        address: 'mail.sko.ai'
        tls: true
        authentication: ''
      appConfig:
        omniauth:
          enabled: true
          autoSignInWithProvider: [authelia]
          syncProfileFromProvider: [authelia]
          allowSingleSignOn: [authelia]
          allowBypassTwoFactor: [authelia]
          syncProfileAttributes: [email]
          blockAutoCreatedUsers: false
          providers: 
            - secret: authelia-oauth2
    # Reduce memory usage
    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 1
      sidekiq:
        minReplicas: 1
        maxReplicas: 1
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
    # Disable things we handle by ourselves
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    grafana:
      enabled: false
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: dummy-app
              spec:
                template:
                  spec:
                    nodeSelector:
                      beta.kubernetes.io/arch: amd64
            target:
              kind: Deployment
          - patch: |-
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: dummy-app
              spec:
                template:
                  spec:
                    nodeSelector:
                      beta.kubernetes.io/arch: amd64
            target:
              kind: StatefulSet
