---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - deployment.yaml
  - advancedsettings.secret.yaml

configMapGenerator:
  - name: kodi-userdata
    files:
      - userdata/sources.xml
