apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- calico/bgppeer.yaml
- calico/calico.yaml
- calico/k8s-api.yaml
- coredns.cm.yaml
- ext-dns.yaml
- nodelocaldns.yaml
- repos/stable.yaml
