apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
- pvc.yaml
- pvc-b.yaml
- service.yaml
- deployment.yaml
- deployment-b.yaml


configMapGenerator:
  - name: bridge-conf
    files:
      - config/mosquitto.conf
