---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jellyfin
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/enable-global-auth: 'false'
spec:
  rules:
    - host: jf.sko.ai
      http:
        paths:
          - backend:
              serviceName: jellyfin
              servicePort: 80
            path: /
