---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jellyfin
  namespace: media
  annotations:
    kubernetes.io/ingress.class: external
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-global-auth: 'false'
spec:
  rules:
    - host: jf.sko.ai
      http:
        paths:
          - backend:
              serviceName: jellyfin
              servicePort: 8096
            path: /
