---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: filebrowser
