---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mojopaste
  namespace: default
  annotations:
    kubernetes.io/ingress.class: internal
spec:
  rules:
    - host: mp.sko.ai
      http:
        paths:
          - backend:
              service:
                name: mojopaste
                port:
                  name: http
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: mojopaste
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: mojopaste
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mojopaste
  namespace: default
  labels:
    app: mojopaste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mojopaste
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mojopaste
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: mojopaste
          image: r.sko.ai/mojopaste:1.0.6
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
          volumeMounts:
            - name: pv-mojopaste
              mountPath: /app/data
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: pv-mojopaste
          persistentVolumeClaim:
            claimName: mojopaste-v3
