---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mojopaste-v3
  namespace: default
spec:
  storageClassName: ssd-raid
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
