---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-server-data-v2
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
