apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- controller.yml
- csi-driver.yml
- namespace.yml
- node.yml
- secret.yaml.enc
- storage-class.yml
- snapshotter/snapshotter.yaml
- snapshotter/volume-snapshot-class.yml
