---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thelounge-v2
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
