---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-storage-data-v2
  namespace: mailserver
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
