---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
      containers:
        - image: ghcr.io/onedr0p/sonarr-develop:4.0.0.334@sha256:6c4e69f7a3d69816b4885437fcf750ab1a7d1b36ff484b20ff7cad03cac10b92
          name: sonarr
          resources:
            requests:
              cpu: 15m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          ports:
            - containerPort: 8989
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: torrents-v2
              mountPath: /torrents
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: torrents-v2
          persistentVolumeClaim:
            claimName: torrents-v2
