---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      strategy: Recreate
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: 6.14.1@sha256:e71cef31dc9fd946c5298cb9155f3a342e29ca855dc1d78f3f3632e821a286be
    podSecurityContext:
      runAsUser: 0
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    enableServiceLinks: false
    env:
      PUID: 1000
      PGID: 1000
    service:
      main:
        ports:
          http:
            port: 8081
          x11: 
            port: 8080
    ingress:
      main:
        enabled: true
        hosts:
          - host: cb.sko.ai
            paths:
              - path: /
                service: 
                  port: 8080
      builtin-web:
        enabled: true
        hosts:
          - host: cb-web.sko.ai
            paths:
              - path: /
                service:
                  port: 8081
    persistence:
      config:
        enabled: true
        existingClaim: calibre-v1
      media:
        enabled: true
        mountPath: /torrents
        existingClaim: torrents-v2
    resources:
      requests:
        cpu: 15m
        memory: 400M
      limits:
        cpu: 800m
        memory: 800M
