kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-v2
  namespace: torrent
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
