apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:32.202.3
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: BINARY_SOURCE
                  value: install
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never
