apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- _namespace.yaml
- ingress-nginx-external.yaml
- ingress-nginx.yaml
- repos/nginx-git.yaml

configMapGenerator:
- name: nginx-template
  files:
  - nginx.tmpl
