apiVersion: batch/v1
kind: CronJob
metadata:
  name: torrent-sort-raku
  namespace: torrent
spec:
  schedule: '*/10 * * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
        spec:
          containers:
          - args:
            - /script/torrent-sort.raku
            command:
            - /usr/bin/raku
            envFrom:
            - secretRef:
                name: kodipass
            image: rakudo-star:2022.07-alpine
            imagePullPolicy: IfNotPresent
            name: torrent-sort
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /script
              name: script
            - mountPath: /media-pv
              name: media-pv
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: torrent-sort-raku
            name: script
          - name: media-pv
            persistentVolumeClaim:
              claimName: torrents-v2
