---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
      containers:
        - image: ghcr.io/onedr0p/prowlarr-nightly:1.1.0.2231@sha256:c1bc5b4c8577daf3bfacda7f6223495f6d8107d787969119b95962110e3ba529
          name: prowlarr
          resources:
            requests:
              cpu: 15m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 9696
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
