---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hdd-raid-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hdd-raid
  resources:
    requests:
      storage: 1Mi
