---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: default
      version: 2.0.2
  interval: 1h
  values:
    image:
      repository: linuxserver/plex
      tag: 1.24.2.4973-2b1b51db9-ls74
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "pl.sko.ai"
      tls:
      - hosts:
        - "pl.sko.ai"
    timezone: "Europe/London"
    advertiseIp: "https://pl.sko.ai"
    persistence:
      config:
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
      transcode:
        enabled: false
        emptyDir:
          medium: "Memory"
      data:
        enabled: false
      extraMounts:
      - name: media-pv
        claimName: nfs-hdd-raid-pvc-v2
    resources:
      requests:
        cpu: 35m
        memory: 1500Mi
      limits:
        cpu: 1000m
        memory: 1500Mi
