---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrents-pv-media
  namespace: media
spec:
  storageClassName: torrents-pv-media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: syno
    path: /volume2/Torrents
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
    - noacl
    - nocto
    - nodiratime
    - rsize=32768
    - wsize=32768
    - async
    - retrans=3
    - timeo=600
