---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: original-photos-v3
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
