kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: original-photos-v2
spec:
  storageClassName: "rook-cephfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
