---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 1h
  ref:
    tag: v6.2.1
  url: https://github.com/kubernetes-csi/external-snapshotter
