apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    random: ENC[AES256_GCM,data:qIZplA==,iv:L3RDdPH344FSRujCd+VNdVarDde+LuYHd1MTTozY4mo=,tag:5aATRd+CgfO9sFK+IG0ltw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-15T12:34:28Z"
    mac: ENC[AES256_GCM,data:iTjnMfgzkIiSEHQ7QT6BY3g6ZfbUTZ+pz9cz1bCe116q6phkaSv8j5fhlCSJeL1jZChjhbQ5ZxMF5JvmJvI7dAtxMUiKE4YNTIzUSbfDUcWOPsbgnEzOhadYnLch+dTNZVlXPhResK//BcLIkywm4DUKjh12u29E9OZ1W6ixUUU=,iv:VuVN/EbzslYaJiytKXAdSNWplJglB6WUfjNKZA5o71E=,tag:1w1Pt8K9NhBwRz9VZtU4AQ==,type:str]
    pgp:
        - created_at: "2021-01-27T10:41:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA4x50yY5upzjEAwAyXUVa7iWCql94DGSI3KQM64kT5At8AZf6wHPvd77MpBU
            lZnLpz368hiw5cnY8klWq5CxY2XQaCT2vFfvfgmr52wtzBfCxgUd0JDuiPv92QVS
            DwBc60U0RzdXHCMPXVbnVHske8vZDCsHPAIZHhjOYZP3HcKJH3dHW1KIn3G1ulZm
            4Wi4GzUnUnX6RlPlPBEtYAnuvPGhLZyNTbvt+VLeaVly7fEOHG0wbkzKye9uWfEm
            dKHJn1t3GSxnbui4D53Fk5WtbU8+hc+IKjaO9HeTglnh0BFP1+bbVP2txO5F/foi
            MQ98Sp2z7XWm3TsbOkeD3kVVJ6QKbJKpSg36z/FhP3ikrkU+dZZAHCaQ70cvrD/G
            ut6EdoayjaSq4OtKtDXuWgZOQjiTN3L095c2oKiskSiSBL02YWGyGRORSQkVo1Rm
            M36TJBdv6yEyKn5ZwaN0k529cWwQbjlvay+RP5oyHAeFWEwgJRu/LzoncVH3jlTd
            Y+z55u0t1ySOQvQSUJfXC/oD9D4cdVS8mVqRQtT4x79lit2jBtihiuzRpPwJBdFG
            fUepmyWaKAeCYktnYPr8rn2l8sGnsfRGdF4Z/D/1YBNnntgqs+VsXYmwAvwekC58
            lD3UHMeRXOiGScyJ2fuqgL9XIhFM/Q06UgyVo9RnMWQbmMK3eVrBvctEpUrY7Owo
            GAyor7W09zDjTgxQyfeZa57OmfNgLV9g+d/yHXbiObru3RRPLNBviq32n7e1yQil
            5NdmlJJtyN2tVb95YB3ChnaC8O276l2bpyhsU2RAQTPEY8vxQBglQJTag7I03Jx2
            L8joqzOTjoYgt5zZsOzfNSEe4zi6QwWt1Fre0y8U9BMvxU9Lj0yshGfrjYUxwKS/
            NHgcby4roy24Q/kju79rLjVna/OCg4W2enNN2+dgFdjDYOH9OhfDwd06Q/9tLgbb
            1fpX1PXeeD0BqeVvHvX5DUAir1JEYQdO+Z8tiPXQ/JQeyd+QMlzgJjzgodJCEsyk
            uOy1TGBAAu6dJmh5nwFCnizSXgEjZfciMa9MI/A4ebZXEyMB3kA//Lqzo3tFsNdQ
            EunYDsqpKcH26LPJXh8IhNER091OhU87nQ/2RHNkmOiZmfY4oR8bMh70SESLOHL3
            xDf3ZXfBu2ZFT8tlMLk4G54=
            =hfJ9
            -----END PGP MESSAGE-----
          fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
