---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc-v3
  namespace: media
spec:
  storageClassName: ssd-raid5
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.1Gi
