---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-pvc-v4
  namespace: default
spec:
  storageClassName: ssd-raid5
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
