---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki-v2
  namespace: monitoring
spec:
  storageClassName: ssd-btrfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
