---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki-v1
  namespace: monitoring
spec:
  storageClassName: ssd-raid5
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
