---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: release-0.9
  url: https://github.com/prometheus-operator/kube-prometheus
