---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - _namespace.yaml
  - setup.yaml
  - flux-repo.yaml
  - graf-ingress.yaml
  - main.yaml
  - prom-ingress.yaml
  - flux-dashboards.yaml
  - loki/
