---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-setup
  interval: 1h0m0s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 2m0s
  patchesStrategicMerge:
    # Add Grafana dashboards and disable password
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
              - name: grafana
                env:
                  - name: GF_AUTH_BASIC_ENABLED
                    value: 'false'
                  - name: GF_AUTH_ANONYMOUS_ENABLED
                    value: 'true'
                  - name: GF_AUTH_ANONYMOUS_ORG_ROLE
                    value: Admin
                volumeMounts:
                  - name: flux-dashboards
                    mountPath: /grafana-dashboard-definitions/0/flux
                  - name: loki-dashboards
                    mountPath: /grafana-dashboard-definitions/0/loki
            volumes:
              - name: flux-dashboards
                configMap:
                  name: grafana-dashboards-flux
                  defaultMode: 420
              - name: loki-dashboards
                configMap:
                  name: loki-logs-dashboard
                  defaultMode: 420
    # Let prometheus scrape all namespaces (like flux-system)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: prometheus-k8s
      rules:
        - apiGroups:
            - ''
          resources:
            - nodes
            - nodes/metrics
            - services
            - endpoints
            - pods
          verbs: [get, list, watch]
        - apiGroups:
            - extensions
          resources:
            - ingresses
          verbs: [get, list, watch]
        - nonResourceURLs:
            - /metrics
          verbs:
            - get
    # Reduce replica counts
    - apiVersion: monitoring.coreos.com/v1
      kind: Alertmanager
      metadata:
        name: main
        namespace: monitoring
      spec:
        replicas: 0
    - apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: k8s
        namespace: monitoring
      spec:
        replicas: 1
    - apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: node-exporter
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
              - name: kube-rbac-proxy
                resources:
                  limits: {}
    - apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-datasources
        namespace: monitoring
      stringData:
        datasources.yaml: |
          {
              "apiVersion": 1,
              "datasources": [
                  {
                      "access": "proxy",
                      "editable": false,
                      "name": "prometheus",
                      "orgId": 1,
                      "type": "prometheus",
                      "url": "http://prometheus-k8s.monitoring.svc:9090",
                      "version": 1
                  },
                  {
                      "access": "proxy",
                      "editable": false,
                      "name": "loki",
                      "orgId": 1,
                      "type": "loki",
                      "url": "http://loki-stack.monitoring.svc:3100",
                      "version": 1
                  }
              ]
          }
