---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-setup
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
  interval: 1h0m0s
  path: ./manifests/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 2m0s
