apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: fluentd-aggregator
  name: fluentd-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-aggregator
  template:
    metadata:
      labels:
        app: fluentd-aggregator
    spec:
      nodeSelector:
        intent: management
      securityContext:
        runAsUser: 2000
      containers:
      - image: ghcr.io/fluent/fluentd-aggregator-docker-image:1.2.0@sha256:5f0af917da731efd5cd787423574d82268432ac674e0adcd4c7d4c39075a674f
        name: fluentd
        resources:
          requests:
            cpu: "50m"
            memory: 0.3Gi
        env:
          - name: FLUENTD_CONF
            value: fluent.conf
        ports:
        - containerPort: 24224
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/
        - name: logging-pvc
          mountPath: /var/log/k8s
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: fluentd-config
      - name: logging-pvc
        persistentVolumeClaim:
          claimName: logging-pvc
