kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: samba-v2
  namespace: media
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
