---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.9 # no-up
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  removeOSDsIfOutAndSafeToRemove: false
  mon:
    count: 3
    allowMultiplePerNode: false
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network:
  crashCollector:
    disable: false
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    port: 7000
    ssl: false
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
  placement:
    osd:
      tolerations:
      - effect: NoExecute
        operator: Exists 
      - effect: NoSchedule
        operator: Exists 
      - effect: PreferNoSchedule
        operator: Exists 
    mon:
      tolerations:
      - effect: NoExecute
        operator: Exists 
      - effect: NoSchedule
        operator: Exists 
      - effect: PreferNoSchedule
        operator: Exists 
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
    nodes:
    - name: "pi0"
      devices:
      - name: "sda5"
    - name: "pi1"
      devices:
      - name: "sda3"
    - name: "pi2"
      devices:
      - name: "sda3"
