kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hass-pvc-v2
  annotations:
    volume.beta.kubernetes.io/storage-class: "rook-ceph-block"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
